bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('posting/', include('posting.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('images/', include('images.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Функция static() подходит только для локальной разработки, но не для применения на боевых серверах.
# Никогда не используйте Django в качестве поставщика статических и медиафайлов.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('analyse_image', views.analyse_image, name='analyse_image'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify


class Image(models.Model):
    # user – указывает пользователя, который добавляет изображение в закладки. Это поле является внешним ключом и
    # использует связь «один ко многим».
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()  # сылка на оригинальное изображение
    image = models.ImageField(upload_to='images/%Y/%m/%d/')  # файл изображения;
    description = models.TextField(blank=True)  # необязательное (blank=True) поле описания
    # <created> – дата и время создания объекта в базе данных.
    # - Аргумент db_index=True говорит Django о необходимости создать индекс по этому полю. Индексы баз данных улучшают
    # производительность. Рассмотрите возможность добавления db_index=True для полей, которые часто используются в
    # filter(), exclude(), order_by().
    # - Для полей с unique=True и ForeignKey индексы создаются автоматически.
    # - Для определения составного индекса можно использовать Meta.index_together
    created = models.DateField(auto_now_add=True, db_index=True)
    # Когда мы определяем поле ManyToManyField, Django создает промежуточную таблицу, содержащую первичные ключи
    # объектов связанных моделей. Этот тип поля предоставляет менеджер отношения «многие ко многим», с помощью которого
    # можно обращаться к связанным объектам в виде     - image.users_like.all()
    # или из объекта пользователя user как             - user.images_likes.all().
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)

    def __str__(self):
        return self.title

    # Мы переопределим метод save() модели Image
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
    # use method save from parent class Image - но т к это название самой модели (Image), то мы сохраняем свой же класс
        super(Image, self).save(*args, **kwargs)
        # функция slugify() автоматически формирует его из переданного заголовка, после чего мы сохраняем объект
        # картинки. Таким образом, слаг будет генерироваться автоматически, юзеру не нужно будет вводить его вручную

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])


class ImageDTO(models.Model):
    image = models.ImageField(upload_to='images/%Y/%m/%d/', blank=True)


class AnalyzedData(object):
    def __init__(self):
        self.r = 0
        self.g = 0
        self.b = 0
        self.model = ''

templates/neural/analyse_image.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load thumbnail %}

{% block content %}
    <link href="{% static "css/analyse_image.css" %}" rel="stylesheet">
    <div id="blog" style="display: block">
        {% if image is None and img is None %}
            <h2>Выберите изображение для анализа</h2>
            <form action="{% url "images:analyse_image" %}" method="post" enctype='multipart/form-data'>
                <p>
                    <input type="file" name="image" accept="image/*" id="id_image">
                </p>
                {% csrf_token %}
                <input name="upload_img" type="submit" value="загрузить изображение">
            </form>
        {% endif %}
        {% if image is not None %}
            <body onload="myFunction()" style="margin:0;">
            {% if wait %}
                <form action="{% url "images:analyse_image" %}?image_loaded" method="get">
                    <input name="image_loaded" type="submit"
                           value="Загрузить результат" class="start_analyze"
                           style="background-color: #609ab6;">
                </form>

            {% else %}
                <form action="{% url "images:analyse_image" %}?image_id={{ pk }}" method="post"
                      enctype='multipart/form-data'>
                    {% csrf_token %}
                    <input name="analyse_img" type="submit"
                           value="Запустить анализ" class="start_analyze">
                </form>
            {% endif %}
            <div class="profile-info" style="padding-bottom: 50px;">
                {% if image is not None %}
                    <img src="{{ image.image.url }}">
                {% endif %}
            </div>
            <div class="loader" id="loader" style="display: none"></div>
        {% endif %}


        {% if img is not None %}
            <div>
                <div class="profile-info" style="width: 100%;">
                    <img src="{{ img }}">
                </div>
            </div>
            <div style="width: 100%;">
                {% for d in img_data %}
                    <div class='box' style="background-color: rgb({{ d.r }},{{ d.g }},{{ d.b }});">
                    </div><p style="margin-left: 30px;">{{ d.model }}</p>
                {% endfor %}
            </div>
            <div style="text-align: center">
                <h2>Бронетехника на изображении</h2>
            </div>
            {% for postd in post_data %}
                <div class="card-body" style="background-color: #ddffdd;
                padding: 10px; margin-top: 20px">
{#                <div class="card shadow bg-white" style="margin-bottom: 10px; margin-top: 10px">#}
{#                    <div style="margin-top: 10px; margin-bottom: 10px;">#}
                        <h2 style="display: inline">{{ postd.model_tag }}</h2>
                        &nbsp&nbsp<a style="color: #5d5d5d; float: right"
                                     href="{% url "blog" %}?tag_value={{ postd.model_tag }}">
                        <i>посмотреть все статьи</i></a>
                        <br><br>
{#                    </div>#}
                    {% if postd.post is not None %}

{#                            <div class="card-body" style="background-color: #ddffdd; padding: 10px">#}
                                <h2 class="card-title" style="margin-top: 20px"><a
                                        href="{% url 'post_detail' pk=postd.post.pk %}">{{ postd.post.title }}</a></h2>
                                <p class="card-text" style="margin-bottom: 5px;"> {{ postd.post.body_summary|striptags }} </p>
                                <hr>
                                <div>
                                    {% if postd.post.tags %}
                                        <b>теги:</b>&nbsp;
                                    {% endif %}
                                    {% for tag in postd.post.tags %}
                                        <a style="color: black"
                                           href="{% url "blog" %}?tag_value={{ tag }}"
                                        ><i>{{ tag }}</i></a>{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                    <div style="text-align: right;"><i>{{ postd.post.created_date }}</i></div>
                                </div>
{#                            </div>#}
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}
    </div>


{% endblock %}

{% block domready %}

    $('input.start_analyze').click(function (e) {
    {#    alert('hello')#}
    document.getElementById("loader").style.display = "block";
    })
{% endblock %}